site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/rbg-todd-test-three
edit_uri: https://github.com/harness-idp-sandbox/rbg-todd-test-three/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core